name: Word

on: push

env:
  inputs: '1.md'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: |
          mkdir output # create output dir
          echo "inputs=${{ env.inputs }}"
      - uses: docker://pandoc/core:2.9
        with:
          args: --output=output/result.docx ${{ env.inputs }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
