name: Advanced Usage

on: push

env:
  output_path: "*.md"

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: |
          mkdir output
          echo "::set-output name=files::$(printf '"%s" ' ${{ env.output_path }})"
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/result.pdf ${{ steps.files_list.outputs.files }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
