name: Convert via Pandoc

on: 
  push:
    branches:
      - master

env:
  src_path: "[[:digit:]]*.md"
  dist_file: index.docx
  reference_file: reference.docx

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: set_variables
        run: |
            echo "::set-output name=src_files::$(printf '"%s" ' ${{ env.src_path }})"
            echo "::set-output name=dist_branch::$(printf '"%s" ' ${GITHUB_REF#refs/heads/}_pandoc"
            mkdir dist
      - uses: docker://pandoc/core:latest
        with:
          args: >-
            --output=dist/${{env.dist_file}}
            --reference-doc=${{env.reference_file}}
            ${{ steps.set_variables.outputs.src_files }}
      - uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: ${{ steps.set_variables.outputs.dist_branch }}
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
