name: Word

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
          echo "::set-output name=files::$(printf '"%s" ' *.md)" # this will also include README.md
      - uses: docker://pandoc/core:2.9
        with:
          args: --output=output/result.docx ${{ steps.files_list.outputs.files }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
